version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:80"
  backend:
    build: 
      context: Email-Service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"